name: help_me_to_speak
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Fonts
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.2.1

  # Widgets
  im_stepper: ^1.0.1+1
  cached_network_image: ^3.2.2
  syncfusion_flutter_datepicker: ^20.3.49
  #Theme


  #Utils
  flutter_screenutil: ^5.5.4

  #Service
  auto_route: ^5.0.2
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
